Test js
Khanetmoi/Portfolio-setup-and-mobile-version-skeleton pull request #14
Opened 2022-03-11 07:59 UTC by Khanetmoi

mobile menu with js

2022-03-11 11:01 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Khanetmoi👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-11 11:01 UTC, thecodechaser commented on index.html
> +            </li>
- [x] Good job on the functionality, but there is a little issue. When the user clicks any of the mobile menu options, the mobile menu should disappear and a correct part of the page should be displayed.
But this functionality is not working. When I click on the menu options the mobile menu is still there. Please make sure when the user clicks any of the mobile menu options, the mobile menu disappears and a correct part of the page should be displayed
 - You may want to add events to your mobile menu options so when any of the event is fired you can use `display: none` for mobile menu

2022-03-11 11:01 UTC, thecodechaser commented on index.html
> +            </li>
- [x] When I open the mobile menu and switch to the desktop screen the mobile menu is still on the screen it should disappear. Please make sure when we switch the screen from mobile to desktop the mobile menu should disappear.
 - You can use media queries for that if the screen cross the min-width you can set your mobile menu `display: none`

### See the image for reference:

![image](https://user-images.githubusercontent.com/83803414/157853775-c74e9048-4a92-4b78-9ea3-e0bb193f6e79.png)

2022-03-11 11:01 UTC, thecodechaser commented on index.html
> +            </li>
- [ ]  Good job the design, But you are supposed to stick to the [figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) design as much as possible. Your design is a little different from the template. Please use correct font size, weight, and correct color for your buttons and make sure it matches the design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/157854145-6ccb6ea5-0fd6-4223-834d-706c117cb5a1.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/157854264-a8b5706a-5599-43f5-801a-50acc161c3df.png)

2022-03-12 19:59 UTC, Deepakdanger approved these changes
Hi @Khanetmoi, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 19:59 UTC, merged